// Generated by https://quicktype.io

export interface Dog {
  breeds: Breed[];
  id: string;
  url: string;
  width: number;
  height: number;
}

export interface Breed {
  weight: Dimension;
  height: Dimension;
  id: number;
  name: string;
  bred_for: string;
  breed_group: string;
  life_span: string;
  temperament: string;
  reference_image_id: string;
}

export interface Dimension {
  imperial: string;
  metric: string;
}
